GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Lex",
    "userID": 3
}

###

PUT http://localhost:3000/api/users
Content-Type: application/json

{
    "userID": 1,
    "nextEmail": "new@new.com"
}

###

DELETE http://localhost:3000/api/users
Content-Type: application/json

{
    "userID": 1
}

###

GET http://localhost:3000/api/users/2