GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Lex",
    "eMail": "lex@lex.com",
    "userID": 3,
    "country": "USA"
}

###

PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "nextEmail": "new@new.com"
}

###

DELETE http://localhost:3000/api/users/1
Content-Type: application/json

{
    "userID": 1
}

###

GET http://localhost:3000/api/users/2