GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Lex",
    "email": "lex@lex.com",
    "country": "USA"
}

###

PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "name": "New Numan",
    "email": "new@new.com",
    "country": "New Zealand"
}

###

DELETE http://localhost:3000/api/users/1

###

GET http://localhost:3000/api/users/1